spring:
  http:
    clients:
      imperative:
        factory: http-components
      connect-timeout: 3s
      read-timeout: 10s
app:
  user:
    base-url: http://localhost:8088
    max-connections-per-route: 20
    max-connections-total: 60
